# Saqib Waheed PIAIC138051

# Numpy_Assignment_2:

# Question:1

### Convert a 1D array to a 2D array with 2 rows?

###### Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [8]:
import numpy as np
from numpy import random

In [11]:
arr1D=np.arange(10)
arr2D=arr1D.reshape(2,5)

print(arr1D)
print("\n")
print(arr2D)

[0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question:2

### How to stack two arrays vertically?

Desired Output::

In [12]:
#array([[0, 1, 2, 3, 4],
#[5, 6, 7, 8, 9],
#[1, 1, 1, 1, 1],
#[1, 1, 1, 1, 1]]

In [13]:
a = ([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b=  ([1, 1, 1, 1, 1],[1, 1, 1, 1, 1])

In [14]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3

## How to stack two arrays horizontally?

###### Desired Output::

In [15]:
# array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       #[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
a=([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])
b=([1, 1, 1, 1, 1],
[1, 1, 1, 1, 1])
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Question:4

## How to convert an array of arrays into a flat 1d array?

###### Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array_2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
result= array_2d.flatten()
print(result)

[0 1 2 3 4 5 6 7 8 9]


# Question:5

### How to Convert higher dimension into one dimension?

###### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [18]:
a =np.arange(0,15).reshape(5,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
Flattened_X = a.flatten()


In [20]:
print(Flattened_X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Question:6

### Convert one dimension to higher dimension?

###### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [21]:
arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
newarr = arr.reshape(5, 3)
newarr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Question:7

### Create 5x5 an array and find the square of an array?

In [23]:
a=np.random.randint(0, 14, size=(5,5)).astype("int")
a

array([[ 8, 10,  2,  8,  1],
       [11,  0,  4,  2,  5],
       [ 1,  6,  3,  1,  7],
       [ 5,  2,  3,  3,  4],
       [ 8,  5,  7, 10,  4]])

In [24]:
print("Square of an array is: \n",np.square(a))

Square of an array is: 
 [[ 64 100   4  64   1]
 [121   0  16   4  25]
 [  1  36   9   1  49]
 [ 25   4   9   9  16]
 [ 64  25  49 100  16]]


# Question:8

### Create 5x6 an array and find the mean?

In [25]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[ 1, 13,  7,  7,  7, 12],
       [12, 13,  9,  7,  3,  7],
       [ 8,  4, 11, 11,  0, 13],
       [10,  9,  6,  8,  2, 12],
       [ 9,  6, 12,  5,  0, 11]])

In [26]:
print("Mean of an array is: \n",np.mean(x))

Mean of an array is: 
 7.833333333333333


# Question:9

### Find the standard deviation of the previous array in Q8?

In [27]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[ 5,  6, 11,  0, 10, 12],
       [10, 10,  5, 12,  2, 13],
       [ 0, 12,  6,  3, 10,  0],
       [ 7,  1, 10,  0,  5,  4],
       [ 5,  0,  6,  5,  7, 10]])

In [28]:
print("Standard Deviation of an array is: \n",np.std(x))

Standard Deviation of an array is: 
 4.152776848755005


# Find the median of the previous array in Q8?

In [29]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[ 0,  9,  2,  9, 10,  1],
       [13,  4,  0,  8,  1,  1],
       [ 6,  0,  0,  2,  2,  5],
       [ 4, 12,  6,  9,  4,  6],
       [ 3,  1,  5,  0,  1,  7]])

In [30]:
print("Median of an array is: \n",np.median(x))

Median of an array is: 
 4.0


# Find the transpose of the previous array in Q8?

In [31]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[ 8,  3, 12,  7,  3, 12],
       [ 5,  2,  0,  7, 12,  4],
       [ 9,  3,  3,  7,  2, 11],
       [ 6,  2,  7,  9,  9,  1],
       [ 4,  4, 11,  7,  1, 11]])

In [32]:
print("Transpose of an array is: \n",np.transpose(x))

Transpose of an array is: 
 [[ 8  5  9  6  4]
 [ 3  2  3  2  4]
 [12  0  3  7 11]
 [ 7  7  7  9  7]
 [ 3 12  2  9  1]
 [12  4 11  1 11]]


# Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [33]:
n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]])
n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [34]:
print("diagonal elements of a matrix: \n") 
diag =np.diagonal(n_array)
diag

diagonal elements of a matrix: 



array([55, 44, 77])

In [35]:
print("\nSum of Diagonal elements is:")
print(sum(diag))


Sum of Diagonal elements is:
176


# Question:13

### Find the determinant of the previous array in Q12?

In [36]:
n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]])
n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [37]:
print("determinant of an array: \n")
deter =np.linalg.det(n_array)
deter


determinant of an array: 



137180.0000000001

# Question:14

### Find the 5th and 95th percentile of an array?

In [38]:
x=np.random.randint(0, 100, size=(100)).astype("int")
x

array([76, 54, 98, 30,  4, 62, 68, 68,  7,  0, 87, 35, 23,  0, 43,  7, 98,
       86,  7, 68, 61, 12,  5, 64, 74, 44, 28, 20, 63, 51, 72, 58, 48, 71,
       80, 93, 72, 49, 12, 53, 84, 24, 48, 11, 62, 76, 62,  7, 46, 92, 38,
        5, 83, 41, 29, 62, 50, 10,  0, 57, 43, 18, 77, 10, 98, 91, 43, 59,
       55, 90, 13, 93, 54, 18, 98, 49, 79, 67, 29, 56, 35, 61, 27, 36,  5,
       92,  9, 80, 52, 74, 50,  5,  1, 33, 16, 98, 71, 35, 32, 82])

In [39]:
np.percentile(x,[5,95])

array([ 4.95, 93.25])

# Question:15

### How to find if a given array has any null values?

In [40]:
n_array = np.empty((3,3))
n_array[:] = np.NaN
print(np.isnan(n_array))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
