# Saqib Waheed PIAIC138051

# Numpy_Assignment_2:

# Question:1

### Convert a 1D array to a 2D array with 2 rows?

###### Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
from numpy import random

In [2]:
a= np.array([[0,1,2,3,4],[5,6,7,8,9]])
b=a.ravel()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question:2

### How to stack two arrays vertically?

Desired Output::

In [3]:
#array([[0, 1, 2, 3, 4],
#[5, 6, 7, 8, 9],
#[1, 1, 1, 1, 1],
#[1, 1, 1, 1, 1]]

In [4]:
a = ([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b=  ([1, 1, 1, 1, 1],[1, 1, 1, 1, 1])

In [5]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3

## How to stack two arrays horizontally?

###### Desired Output::

In [6]:
# array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       #[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [7]:
a=([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])
b=([1, 1, 1, 1, 1],
[1, 1, 1, 1, 1])
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Question:4

## How to convert an array of arrays into a flat 1d array?

###### Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array_2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
result= array_2d.flatten()
print(result)

[0 1 2 3 4 5 6 7 8 9]


# Question:5

### How to Convert higher dimension into one dimension?

###### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [9]:
a =np.arange(0,15).reshape(5,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
Flattened_X = a.flatten()


In [11]:
print(Flattened_X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Question:6

### Convert one dimension to higher dimension?

###### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [12]:
arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
newarr = arr.reshape(5, 3)
newarr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Question:7

### Create 5x5 an array and find the square of an array?

In [14]:
a=np.random.randint(0, 14, size=(5,5)).astype("int")
a

array([[ 3,  2, 10,  9, 11],
       [ 9,  2,  4,  4,  2],
       [ 7,  7, 11,  6,  1],
       [ 8,  0,  4,  1, 10],
       [ 1,  3,  4,  0, 13]])

In [15]:
print("Square of an array is: \n",np.square(a))

Square of an array is: 
 [[  9   4 100  81 121]
 [ 81   4  16  16   4]
 [ 49  49 121  36   1]
 [ 64   0  16   1 100]
 [  1   9  16   0 169]]


# Question:8

### Create 5x6 an array and find the mean?

In [16]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[10,  1, 13,  2,  4, 11],
       [11,  8,  3,  9,  2,  5],
       [ 4,  4,  6, 12, 12, 13],
       [ 7,  8,  7, 12, 10,  6],
       [ 1,  5, 13,  2,  1,  1]])

In [17]:
print("Mean of an array is: \n",np.mean(x))

Mean of an array is: 
 6.766666666666667


# Question:9

### Find the standard deviation of the previous array in Q8?

In [18]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[ 4,  1, 11,  6,  1, 10],
       [ 4,  6,  4,  3,  4, 10],
       [13,  6,  0, 11, 11,  4],
       [ 4,  1, 12,  3,  4,  8],
       [10,  4,  6,  3,  4, 13]])

In [19]:
print("Standard Deviation of an array is: \n",np.std(x))

Standard Deviation of an array is: 
 3.8077406541003933


# Find the median of the previous array in Q8?

In [20]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[12,  5,  6,  0,  8,  7],
       [13, 13,  2,  6,  3,  8],
       [ 9, 10,  9,  3, 10, 13],
       [ 3,  5,  4,  9, 11,  0],
       [10,  2,  6, 12,  6,  6]])

In [21]:
print("Median of an array is: \n",np.median(x))

Median of an array is: 
 6.5


# Find the transpose of the previous array in Q8?

In [22]:
x=np.random.randint(0, 14, size=(5,6)).astype("int")
x

array([[13,  2,  7,  4,  4,  1],
       [ 1,  8,  9,  5,  7,  5],
       [ 5, 10, 13,  5, 10,  3],
       [ 5, 11,  0, 12, 13,  9],
       [12,  3,  4,  0,  5,  8]])

In [23]:
print("Transpose of an array is: \n",np.transpose(x))

Transpose of an array is: 
 [[13  1  5  5 12]
 [ 2  8 10 11  3]
 [ 7  9 13  0  4]
 [ 4  5  5 12  0]
 [ 4  7 10 13  5]
 [ 1  5  3  9  8]]


# Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [24]:
n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]])
n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [25]:
print("diagonal elements of a matrix: \n") 
diag =np.diagonal(n_array)
diag

diagonal elements of a matrix: 



array([55, 44, 77])

In [26]:
print("\nSum of Diagonal elements is:")
print(sum(diag))


Sum of Diagonal elements is:
176


# Question:13

### Find the determinant of the previous array in Q12?

In [27]:
n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]])
n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [28]:
print("determinant of an array: \n")
deter =np.linalg.det(n_array)
deter


determinant of an array: 



137180.0000000001

# Question:14

### Find the 5th and 95th percentile of an array?

In [29]:
x=np.random.randint(0, 100, size=(100)).astype("int")
x

array([95, 71, 59, 33, 16, 71, 94,  5, 66,  4, 23, 42,  1, 31, 57, 95,  7,
       35, 56,  4, 51, 24, 94, 31, 52, 29, 67, 77, 44, 21, 68, 69, 63, 52,
       64, 99, 33, 21, 99, 10, 58, 37, 27,  9, 29, 22, 94, 39, 88, 25, 15,
       69, 74, 48, 16, 34, 51, 34, 22, 30, 87, 31,  9, 11, 72, 94, 77, 13,
       40,  1, 80, 14, 54, 61, 36, 21, 65, 13, 69,  5, 66, 18, 85, 17, 10,
       57, 14, 79, 33, 90, 27, 76,  7, 99, 58, 21, 63, 32, 59, 96])

In [30]:
np.percentile(x,[5,95])

array([ 5., 95.])

# Question:15

### How to find if a given array has any null values?

In [31]:
B=np.arange(25).reshape(5, 5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [309]:
print("\nIs NaN: \n", np.isnan(B))


Is NaN: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
