   # Saqib Waheed PIAIC138051


###### 1. Import the numpy package under the name np

In [349]:
import numpy as np
from numpy import random

###### 2. Create a null vector of size 10

In [350]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 3.Create a vector with values ranging from 10 to 49

In [351]:
testArr = np.array(range(10,50))
testArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###### 4. Find the shape of previous array in question 3

In [352]:
np.shape(testArr)

(40,)

5.Print the type of the previous array in question 3

In [353]:
testArr.dtype

dtype('int64')

###### 5.Print the numpy version and the configuration


In [354]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


###### 6.Print the dimension of the array in question 3

In [355]:
testArr.ndim

1

###### 7.Create a boolean array with all the True values

In [356]:
bool_arr = np.array([1, 0.5,True,"empty"], dtype=bool)
print(bool_arr)

[ True  True  True  True]


###### 8.Create a two dimensional array

In [357]:
arr2d = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

###### 9.Create a three dimensional array

In [358]:
a3dimensional = np.zeros((2, 3, 4))
a3dimensional

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

###### 10.Reverse a vector (first element becomes last)

In [359]:
orginal =np.arange(0,20)
print("Orignal array")
print(orginal)
print("Reverse array")
reverse =orginal[::-1]
print(reverse)

Orignal array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse array
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


###### 11.Create a null vector of size 10 but the fifth value which is 1

In [360]:
x=np.array(range(10))
print(x)
print("Updating fifth Value which is '1' ")
x[4]=1
print(x)

[0 1 2 3 4 5 6 7 8 9]
Updating fifth Value which is '1' 
[0 1 2 3 1 5 6 7 8 9]


###### 12.Create a 3x3 identity matrix

In [361]:
array_2d =np.identity(3)
print("3x3 Matrix")
array_2d

3x3 Matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###### 13. arr = np.array([1, 2, 3, 4, 5])


###### Convert the data type of the given array from int to float

In [362]:
arr = np.array([1, 2, 3, 4, 5],(np.float32))
print(arr)

[1. 2. 3. 4. 5.]


###### 14. Multiply arr1 with arr2

In [363]:
arr1 = np.array([[1.,2.,3],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

###### 15 Make an array by comparing both the arrays provided above

In [364]:
arr1 = np.array([[1.,2.,3],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
comparison = arr1==arr2
arr3 = comparison.all()
print(arr3)

False


###### 16.Extract all odd numbers from arr with values(0-9)

In [365]:
a=np.array(range(0,10))
a[a%2==1]

array([1, 3, 5, 7, 9])

###### 17.Replace all odd numbers to -1 from previous array

In [366]:
a=np.array([1, 3, 5, 7, 9])
a[a%2==1] = -1
print(a)

[-1 -1 -1 -1 -1]


###### 18. arr = np.arange(10)

###### Replace the values of indexes 5,6,7 and 8 to 12

###### 19.Create a 2d array with 1 on the border and 0 inside

In [367]:
x=np.ones((5,5))
print("Orginal array")
print(x)
print("1 on the border and 0 inside in the arry")
x[1:-1,1:-1]=0
print(x)

Orginal array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the arry
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### 20. arr2d=np.array([[1,2,3],[4,5,6][7,8,9]])

###### Replace the value 5 to 12

In [368]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Orignal Array")
print(arr2d)
print("Replace 5 with 12")
arr2d[1,1]=12
print(arr2d)

Orignal Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Replace 5 with 12
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


###### 21.arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

###### Convert all the values of 1st array to 64

In [369]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original")
print(arr3d)
print("Convert all the values of 1st array to 64")
arr3d[0]=64
print(arr3d)

Original
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Convert all the values of 1st array to 64
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


###### 22. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it


In [370]:
arr2d=np.arange(10).reshape(2,5)
print("This is 2-Dimensional array with values 0-9")
print(arr2d)
print("This is 1st 1-D array")
raveled_arr1d=arr2d.ravel()
raveled_arr1d

This is 2-Dimensional array with values 0-9
[[0 1 2 3 4]
 [5 6 7 8 9]]
This is 1st 1-D array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 23.Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [371]:
arr2d=np.arange(10).reshape(2,5)
print(arr2d)
arr2d[0,2]


[[0 1 2 3 4]
 [5 6 7 8 9]]


2

###### 24.Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [372]:
arr2d=np.arange(10).reshape(2,5)
print(arr2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [373]:
arr2d[:,3]

array([3, 8])

###### 25.Create a 10x10 array with random values and find the minimum and maximum values

In [374]:
x=np.random.randint(10, size=(10,10))
print(x)
print("Minimum value in the whole array:%d"%(x.min()))
print("Minimum value in the whole array:%d"%(x.max()))

[[9 2 9 9 5 6 4 8 8 1]
 [9 8 7 5 0 8 0 4 0 9]
 [5 5 1 6 1 7 2 8 8 1]
 [0 9 3 3 5 7 3 2 8 4]
 [4 9 6 7 1 6 3 3 2 9]
 [1 3 7 0 8 0 5 4 8 3]
 [7 5 7 1 4 8 4 4 6 8]
 [1 3 3 6 1 2 1 9 7 7]
 [2 5 1 1 7 8 9 1 5 4]
 [4 9 6 2 3 8 7 9 8 5]]
Minimum value in the whole array:0
Minimum value in the whole array:9


###### 26. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8]

###### Find the common items between a and b
                                                 

In [375]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


###### 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

###### Find the positions where elements of a and b match

In [376]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a,b))[0]

array([1, 3, 5, 7])

###### 28. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

###### Find all the values from array data where the values from array names are not equal to Will

In [377]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [378]:
x=np.where(names != "Will")
print(x)

(array([0, 1, 3, 5, 6]),)


###### 29. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

###### Find all the values from array data where the values from array names are not equal to Will and Joe

In [379]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
x=[names != "Will",2],[names != 'Joe',3]
print(x)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.92328531  0.69119276 -1.67880436  0.62593013]
 [-1.09127503 -0.56676413 -0.37076999  0.71084155]
 [-0.24453774 -1.02929338 -1.13864537  1.13582528]
 [ 2.43927016 -0.84698807 -0.40999767 -0.52697815]
 [-1.00404534 -0.074182   -0.23552905 -1.81596186]
 [ 1.28626243  0.50638739  0.17668362  0.33621626]
 [ 0.22202247 -0.15009082 -2.5161183   0.09132776]]
([array([ True,  True, False,  True, False,  True,  True]), 2], [array([ True, False,  True,  True,  True, False, False]), 3])


###### 30.Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15

In [380]:
np.random.randint(1, 14, size=(5,3)).astype("float") / 10

array([[0.2, 1.3, 0.2],
       [0.3, 1.3, 0.1],
       [1.2, 0.3, 0.8],
       [0.7, 1.2, 0.2],
       [0.7, 0.3, 1.2]])

###### 31. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [381]:
y=np.arange(0,16).reshape(2,2,4).astype("float")
y

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

###### 32. Swap axes of the array you created in Question 31

In [382]:
y=np.arange(0,16).reshape(2,2,4).astype("float")
y.T

array([[[ 0.,  8.],
        [ 4., 12.]],

       [[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]]])

###### 33. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [383]:
point =np.arange(10)
print("array of size Ten",point)

array of size Ten [0 1 2 3 4 5 6 7 8 9]


In [384]:
print("Square root of every elements")
z=np.sqrt(point)
print(z)

Square root of every elements
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [385]:
print("values less than 0.5, replace them with 0")
np.where(point<0.5,0,point )

values less than 0.5, replace them with 0


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 34.Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [386]:
x=random.randint(13)

x

11

In [387]:
y=random.randint(13)
y

12

In [388]:
print(np.maximum(x,y))

12


###### 35. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

###### Find the unique names and sort them out!

In [389]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe',])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

###### 36.a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

###### From array a remove all items present in array b

In [390]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

###### 37 . Following is the input NumPy array delete column two and insert following new column in its place.

###### sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

###### newColumn = numpy.array([[10,10,10]])

In [391]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray.reshape(3,3)

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [392]:
x=np.delete(sampleArray, 2)
x.reshape(2,4)

array([[34, 43, 82, 22],
       [12, 53, 94, 66]])

In [393]:
column_to_be_added = [10,10,10]
sampleArray = np.append( x,column_to_be_added)
sampleArray

array([34, 43, 82, 22, 12, 53, 94, 66, 10, 10, 10])

###### 38.  x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

###### Find the dot product of the above two matrix

In [394]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [395]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

######  39. Generate a matrix of 20 random values and find its cumulative sum

In [396]:
x=np.random.randint(20, size=(10,10))

In [397]:
x

array([[17, 13,  4,  0, 14, 16,  8, 18,  6,  2],
       [ 0, 15,  9, 17,  4,  4, 10,  0, 19, 13],
       [ 2,  5,  1, 13,  8,  5, 12,  5,  6,  0],
       [ 3, 14,  5,  1,  8,  2, 10, 19, 13,  0],
       [ 9,  2,  6, 15,  2, 10, 18, 14, 11,  4],
       [ 4, 11, 12, 16, 11, 13, 14,  8,  8, 12],
       [16, 12, 14, 15, 11,  1, 14,  3, 12,  9],
       [ 2, 15,  7, 14,  8,  3, 12,  9, 19, 19],
       [ 6,  0, 13,  4,  0, 10, 14,  1, 19, 14],
       [13, 12, 19, 19, 16, 12,  9,  1, 19,  3]])

In [398]:
np.cumsum(x,dtype=int)

array([ 17,  30,  34,  34,  48,  64,  72,  90,  96,  98,  98, 113, 122,
       139, 143, 147, 157, 157, 176, 189, 191, 196, 197, 210, 218, 223,
       235, 240, 246, 246, 249, 263, 268, 269, 277, 279, 289, 308, 321,
       321, 330, 332, 338, 353, 355, 365, 383, 397, 408, 412, 416, 427,
       439, 455, 466, 479, 493, 501, 509, 521, 537, 549, 563, 578, 589,
       590, 604, 607, 619, 628, 630, 645, 652, 666, 674, 677, 689, 698,
       717, 736, 742, 742, 755, 759, 759, 769, 783, 784, 803, 817, 830,
       842, 861, 880, 896, 908, 917, 918, 937, 940])